# Generated by Django 5.0.6 on 2024-08-28 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف روی فاکتور'),
        ),
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 28, 12, 17, 11, 863764), verbose_name='تاریخ درج سفارش'),
        ),
    ]
