# Generated by Django 5.0.6 on 2024-09-02 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymenttype_order_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 15, 39, 4, 929807), verbose_name='تاریخ درج سفارش'),
        ),
    ]
