# Generated by Django 5.0.6 on 2024-09-02 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 15, 47, 55, 938744), verbose_name='تاریخ درج سفارش'),
        ),
    ]
