# Generated by Django 5.0.6 on 2024-09-03 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 17, 28, 0, 786371), verbose_name='تاریخ درج سفارش'),
        ),
    ]
