# Generated by Django 5.0.6 on 2024-09-08 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_register_date_alter_orderdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 15, 5, 49, 100543), verbose_name='تاریخ درج سفارش'),
        ),
    ]
