# Generated by Django 5.0.6 on 2024-09-14 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 14, 25, 42, 188563), verbose_name='تاریخ درج سفارش'),
        ),
    ]
