# Generated by Django 5.0.6 on 2024-09-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
