# Generated by Django 5.0.6 on 2024-09-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_coupen_discount_alter_discountbasket_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
    ]
