# Generated by Django 5.0.6 on 2024-09-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_rename_coupen_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupen_code',
            new_name='coupon_code',
        ),
    ]
