# Generated by Django 5.0.6 on 2024-09-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_brand_image_name_alter_product_image_name_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='products.product', verbose_name='کالا'),
        ),
    ]
