# Generated by Django 5.0.6 on 2024-10-11 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_warehouse_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='user_registered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseuser_registered', to=settings.AUTH_USER_MODEL, verbose_name='ادمین'),
        ),
    ]
